spring.application.name=microservicio-notificaciones
server.port = 8009
#server.port=8029
spring.datasource.url=jdbc:mysql://localhost:3306/notificacion_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.showsql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=janori425@gmail.com
spring.mail.password=kotlaxwdidnrphto

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

